//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaApp.WebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceRef.UebSherbimiSoap")]
    public interface UebSherbimiSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LigaApp.WebServiceRef.HelloWorldResponse HelloWorld(LigaApp.WebServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.HelloWorldResponse> HelloWorldAsync(LigaApp.WebServiceRef.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetMenaxhimiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenaxhimi", ReplyAction="*")]
        LigaApp.WebServiceRef.GetMenaxhimiResponse GetMenaxhimi(LigaApp.WebServiceRef.GetMenaxhimiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenaxhimi", ReplyAction="*")]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetMenaxhimiResponse> GetMenaxhimiAsync(LigaApp.WebServiceRef.GetMenaxhimiRequest request);
        
        // CODEGEN: Generating message contract since element name GetRegjistrimiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegjistrimi", ReplyAction="*")]
        LigaApp.WebServiceRef.GetRegjistrimiResponse GetRegjistrimi(LigaApp.WebServiceRef.GetRegjistrimiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegjistrimi", ReplyAction="*")]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetRegjistrimiResponse> GetRegjistrimiAsync(LigaApp.WebServiceRef.GetRegjistrimiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LigaApp.WebServiceRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LigaApp.WebServiceRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenaxhimiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenaxhimi", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.GetMenaxhimiRequestBody Body;
        
        public GetMenaxhimiRequest() {
        }
        
        public GetMenaxhimiRequest(LigaApp.WebServiceRef.GetMenaxhimiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMenaxhimiRequestBody {
        
        public GetMenaxhimiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenaxhimiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenaxhimiResponse", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.GetMenaxhimiResponseBody Body;
        
        public GetMenaxhimiResponse() {
        }
        
        public GetMenaxhimiResponse(LigaApp.WebServiceRef.GetMenaxhimiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMenaxhimiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetMenaxhimiResult;
        
        public GetMenaxhimiResponseBody() {
        }
        
        public GetMenaxhimiResponseBody(System.Xml.Linq.XElement GetMenaxhimiResult) {
            this.GetMenaxhimiResult = GetMenaxhimiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegjistrimiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegjistrimi", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.GetRegjistrimiRequestBody Body;
        
        public GetRegjistrimiRequest() {
        }
        
        public GetRegjistrimiRequest(LigaApp.WebServiceRef.GetRegjistrimiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRegjistrimiRequestBody {
        
        public GetRegjistrimiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegjistrimiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegjistrimiResponse", Namespace="http://tempuri.org/", Order=0)]
        public LigaApp.WebServiceRef.GetRegjistrimiResponseBody Body;
        
        public GetRegjistrimiResponse() {
        }
        
        public GetRegjistrimiResponse(LigaApp.WebServiceRef.GetRegjistrimiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRegjistrimiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetRegjistrimiResult;
        
        public GetRegjistrimiResponseBody() {
        }
        
        public GetRegjistrimiResponseBody(System.Xml.Linq.XElement GetRegjistrimiResult) {
            this.GetRegjistrimiResult = GetRegjistrimiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UebSherbimiSoapChannel : LigaApp.WebServiceRef.UebSherbimiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UebSherbimiSoapClient : System.ServiceModel.ClientBase<LigaApp.WebServiceRef.UebSherbimiSoap>, LigaApp.WebServiceRef.UebSherbimiSoap {
        
        public UebSherbimiSoapClient() {
        }
        
        public UebSherbimiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UebSherbimiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UebSherbimiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UebSherbimiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LigaApp.WebServiceRef.HelloWorldResponse LigaApp.WebServiceRef.UebSherbimiSoap.HelloWorld(LigaApp.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LigaApp.WebServiceRef.HelloWorldRequest inValue = new LigaApp.WebServiceRef.HelloWorldRequest();
            inValue.Body = new LigaApp.WebServiceRef.HelloWorldRequestBody();
            LigaApp.WebServiceRef.HelloWorldResponse retVal = ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.HelloWorldResponse> LigaApp.WebServiceRef.UebSherbimiSoap.HelloWorldAsync(LigaApp.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LigaApp.WebServiceRef.HelloWorldResponse> HelloWorldAsync() {
            LigaApp.WebServiceRef.HelloWorldRequest inValue = new LigaApp.WebServiceRef.HelloWorldRequest();
            inValue.Body = new LigaApp.WebServiceRef.HelloWorldRequestBody();
            return ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LigaApp.WebServiceRef.GetMenaxhimiResponse LigaApp.WebServiceRef.UebSherbimiSoap.GetMenaxhimi(LigaApp.WebServiceRef.GetMenaxhimiRequest request) {
            return base.Channel.GetMenaxhimi(request);
        }
        
        public System.Xml.Linq.XElement GetMenaxhimi() {
            LigaApp.WebServiceRef.GetMenaxhimiRequest inValue = new LigaApp.WebServiceRef.GetMenaxhimiRequest();
            inValue.Body = new LigaApp.WebServiceRef.GetMenaxhimiRequestBody();
            LigaApp.WebServiceRef.GetMenaxhimiResponse retVal = ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).GetMenaxhimi(inValue);
            return retVal.Body.GetMenaxhimiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetMenaxhimiResponse> LigaApp.WebServiceRef.UebSherbimiSoap.GetMenaxhimiAsync(LigaApp.WebServiceRef.GetMenaxhimiRequest request) {
            return base.Channel.GetMenaxhimiAsync(request);
        }
        
        public System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetMenaxhimiResponse> GetMenaxhimiAsync() {
            LigaApp.WebServiceRef.GetMenaxhimiRequest inValue = new LigaApp.WebServiceRef.GetMenaxhimiRequest();
            inValue.Body = new LigaApp.WebServiceRef.GetMenaxhimiRequestBody();
            return ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).GetMenaxhimiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LigaApp.WebServiceRef.GetRegjistrimiResponse LigaApp.WebServiceRef.UebSherbimiSoap.GetRegjistrimi(LigaApp.WebServiceRef.GetRegjistrimiRequest request) {
            return base.Channel.GetRegjistrimi(request);
        }
        
        public System.Xml.Linq.XElement GetRegjistrimi() {
            LigaApp.WebServiceRef.GetRegjistrimiRequest inValue = new LigaApp.WebServiceRef.GetRegjistrimiRequest();
            inValue.Body = new LigaApp.WebServiceRef.GetRegjistrimiRequestBody();
            LigaApp.WebServiceRef.GetRegjistrimiResponse retVal = ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).GetRegjistrimi(inValue);
            return retVal.Body.GetRegjistrimiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetRegjistrimiResponse> LigaApp.WebServiceRef.UebSherbimiSoap.GetRegjistrimiAsync(LigaApp.WebServiceRef.GetRegjistrimiRequest request) {
            return base.Channel.GetRegjistrimiAsync(request);
        }
        
        public System.Threading.Tasks.Task<LigaApp.WebServiceRef.GetRegjistrimiResponse> GetRegjistrimiAsync() {
            LigaApp.WebServiceRef.GetRegjistrimiRequest inValue = new LigaApp.WebServiceRef.GetRegjistrimiRequest();
            inValue.Body = new LigaApp.WebServiceRef.GetRegjistrimiRequestBody();
            return ((LigaApp.WebServiceRef.UebSherbimiSoap)(this)).GetRegjistrimiAsync(inValue);
        }
    }
}
